name: Daily Clipper Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies (ffmpeg for moviepy)
      run: sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Recreate client_secret.json dari Secrets
      env:
        SECRET_DATA: ${{ secrets.CLIENT_SECRET_JSON }}
      run: |
        echo "$SECRET_DATA" > client_secret.json

    - name: Recreate token.json dari Secrets
      env:
        TOKEN_DATA: ${{ secrets.TOKEN_JSON }}
      run: |
        mkdir -p config
        echo "$TOKEN_DATA" > config/token.json

    - name: Recreate YouTube cookies
      env:
            COOKIES_DATA: ${{ secrets.YOUTUBE_COOKIES }}
      run: |
        echo "$COOKIES_DATA" > cookies.txt
        
    - name: Run main pipeline
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python main.py
